### ISSUE TITLE
Doesn't handle disconnects

### ISSUE THREAD

**Issue by FayneAldan** [xhayper/discord-rpc#42]
**Describe the bug**
This library doesn't handle disconnects and fails to reconnect when Discord is restarted.

**To Reproduce**
1. Run any RPC program using this library
2. Exit and reopen Discord

**Expected behavior**
Discord RPC detects the disconnect and attempts to re-connect to Discord.

**Screenshots**
N/a

**(please complete the following information):**
 - OS: Windows
 - OS Version: Windows 11 Pro
 - Discord Version: Stable 165485

**Additional context**
The program I used for testing has an event handler for `disconnected`, but it's never fired:
https://github.com/FayneAldan/lastfm-rp/blob/3d8e34f86ba94fdacc4b6adc66f0036045bee66c/src/index.ts#L58-L60

**Comment by xhayper** [comment]
I will figure out how to fix this.

**Comment by xhayper** [comment]
discord-rpc won't handle reconnect logic because it's up to you to implement it, because different developer have a different way to restart their instance, there's a bug that caused `disconnected` to not be called, which i have fixed in 81b6538.
