### ISSUE TITLE
RPC_OAUTH2_ERROR

### ISSUE THREAD

**Issue by mateie** [xhayper/discord-rpc#50]
I have followed one of the OAuth Examples within this github repo and I am getting the error

`RPC_OAUTH2_ERROR: OAuth2 Error: invalid_request: Missing "redirect_uri" in request.`

I have tried adding _redirect_uri_ within the **login** method but I get a different error

`RPC_OAUTH2_ERROR: Redirect URI cannot be used in the RPC OAuth2 Authorization flow`

If this issue is not module problem, please help if possible, if not it's okay as well.

Thank you ^^

**Comment by xhayper** [comment]
I am currently unsure if discord actually support oauth for rpc, but i will take a look into this

**Comment by xhayper** [comment]
discord rpc is a messy work with very inaccurate / incomplete documentation

**Comment by mateie** [comment]
Thank you so much. If you have further questions or you want me to do other things or you want me to figure this out myself I am willing to contribute. Thank you ^^

**Comment by xhayper** [comment]
if i remember correctly, back when i wrote the example, i don't have to set redirect url at all, so maybe that have changed?

**Comment by mateie** [comment]
That would make sense. But it doesn't make sense that it is asking for redirect uri and then when its given to it, it rejects it.

**Comment by xhayper** [comment]
Yes, it is really confusing

**Comment by xhayper** [comment]
Okay i am sorry for being a year late, but i have figured everything out.
You can check out the new example here.

https://github.com/xhayper/discord-rpc/commit/ccfddeef9d7a05e3fc6f8cc2770c347a2278e060
