### ISSUE TITLE
Buffer Out-of-Bounds Error and Discord Closure Crash

### ISSUE THREAD

**Issue by RagnarLothbrok-Odin** [xhayper/discord-rpc#55]
**Describe the bug**
Upon closing Discord, the application crashes with a buffer out-of-bounds error.

**To Reproduce**
1. Launch the application.
2. Connect to Discord.
3. Client.user.setActivity()
4. Close Discord.
5. Observe the buffer out-of-bounds error.

**Expected behavior**
The application should gracefully handle disconnects upon closing Discord, allowing for appropriate cleanup or reconnection logic.
I attempted to catch this issue with both `on('ERROR')` and `on('disconnect')` to no avail.

**Source code**
So you understand my use case, my source is here: https://github.com/RagnarLothbrok-Odin/TraktDiscordPresence/blob/main/src/index.ts#L203
My changes almost look identical, just changed some things to work with your fork.

**(please complete the following information):**
 - OS: macOS
 - OS Version: macOS 14.3
 - Discord Version: Latest stable
 
**Additional context**
My use case:
```typescript
// Function A
rpc = new Client({
                clientId: traktCredentials.discordClientId,
                transport: {
                    type: 'ipc',
                },
            });

rpc.on('ready', async () => {
                instanceState = ConnectionState.Connected;
                if (progressBar)progressBar.stop();
                progressBar = await generateProgressBar();
                progressBar.start(0, 0);
            });
            
await rpc.login();

// Function B
// Check if the RPC transport socket is connected
        if (!rpc.transport.isConnected) {
            rpc = null;

            // Respawn the RPC client (Function A)
            await new DiscordRPC().spawnRPC(this);
            return;
        }
```

**Comment by xhayper** [comment]
Cam you post the stacktrace here

**Comment by xhayper** [comment]
Got it.

**Comment by xhayper** [comment]
Use the `rpc.on("debug", console.debug)` to figure out what is causing the issue, i am putting out a patch for `Out-of-Bounds`
