### ISSUE TITLE
`ClientUser#fetchChannels` returns the wrong type.

### ISSUE THREAD

**Issue by LeoCatsune** [xhayper/discord-rpc#56]
In the code referenced below, `ClientUser#fetchChannels` returns `Promise<Channel>`, but the actual data should be an array: `Promise<Channel[]>`.

https://github.com/xhayper/discord-rpc/blob/6a848e23e3bf1a989a1b4635ce6ae1c5d6cd887f/src/structures/ClientUser.ts#L126-L135

See the documentation for [`GET_CHANNELS`](https://discord.com/developers/docs/topics/rpc#getchannels).

**Comment by xhayper** [comment]
Fixed
