### ISSUE TITLE
Not enough package during installation

### ISSUE THREAD

**Issue by kostya-main** [xhayper/discord-rpc#63]
After building the application, an error occurs:
`Error: Could not resolve "bufferutil" imported by "ws". Is it installed?`
Also with the utf-8-validate package. Please rebuild the package without these dependencies or return them to package.json

**Comment by xhayper** [comment]
What library are you using to build the application? Webpack? Vite?

**Comment by kostya-main** [comment]
I use Vite library.

**Comment by xhayper** [comment]
Maybe you can try externalizing your project, if that doesn't work, i can try readding the optional dependencies

**Comment by kostya-main** [comment]
After installing bufferutil and utf-8-validate in my project, everything works correctly. It just seems to me that I have to install them necessarily, although they are optional.

**Comment by kostya-main** [comment]
As a result, I made a [fork](https://github.com/kostya-main/discord-rpc) and using esbuild disabled the import of utf-8-validate and bufferutil.
